### ISSUE TITLE
waitgroup使用有问题

### ISSUE THREAD

**Issue by woodyxiong** [onewesong/downloadSpeedBench#1]
https://github.com/onewesong/downloadSpeedBench/blob/ea6d52c519294ac965f5330b8ed1922001a34157/main.go#L37

一个http请求不成功的话，waitgroup会一直阻塞，wg.Done应放到defer里

**Comment by onewesong** [comment]
你没看懂选点的逻辑
wg.Add了10个，成功才-1，10个成功就完成了选点的逻辑（选出了响应最快的10个点）
如果放到defer里，失败也-1，就会选到有问题的点
